name: cms_server
description: Serves markdown files
version: 0.0.2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  aqueduct: ^3.0.0
  json_serializable: ^3.0.0
  json_annotation: ^2.4.0
  common:
    git:
      url: git://github.com/ericwindmill/flutter_by_example.git
      path: common

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0