name: models
description: Biz Objects for the recurring todo app corporation

# IMPORTANT:
# This package should not depend on _anything_ that makes it platform dependent.
# This package should not depend on _anything_ else from the business.

environment:
  sdk: '>=2.7.0 <3.0.0'
  json_annotation: ^3.0.0


dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  json_serializable: ^3.2.0
  build_runner: ^1.0.0
