name: common
version: 1.0.0+5
description: Common classes for client side and server side
homepage: https://www.flutterbyexample.com
author: Eric Windmill <eric@ericwindmill.com>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.4.1
  rxdart: ^0.22.0
  meta: any
  bloc: ^0.14.1
  json_serializable: ^3.0.0
  json_annotation: ^2.4.0
  equatable: ^0.2.6
  http: ^0.12.0
  markdown: ^2.0.0
  yaml: ^2.0.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  build_runner: any
  build_web_compilers: ^2.8.0