name: common
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Your Name <eric@ericwindmill.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  path: ^1.4.1
  rxdart: ^0.22.0
  meta: any
  bloc: ^0.14.1
  json_serializable: ^3.0.0
  json_annotation: ^2.4.0
  equatable: ^0.2.6
  http: ^0.12.0
  markdown: ^2.0.0
  yaml: ^2.0.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  build_runner: any
  build_web_compilers: ^0.4.0